language: python
python:
- '3.6'
- '3.5'
- '2.7'
sudo: required
services:
- docker
install:
- pip install -r requirements.txt
before_script:
- docker run -d -p 127.0.0.1:1883:1883 thethingsnetwork/rabbitmq
script:
- pycodestyle --first src
before_deploy:
- python setup.py sdist
- python setup.py bdist_wheel --universal
deploy:
  provider: pypi
  user: emmlejeail
  password:
    secure: rKECpL6O1cMOjG39HE2tAx+5/SAngQPYbYnO1JXjXubP6rgg1d59fGTCkL/lqdENiF1YDCZGO3mHAXJAYzOK7kC6o0bN/hmz+j+7VNBTLu7s8dEQZebSBuizKYVj6sUDBO7BIxSZ2E9JZUnh1+l/RRaJ1B2BYlK8QJhsO2ENlf1RRhgZxaBEHDaeKzcxNzcWQrIALpsBokE/05iZgRtoGaOjo1ZTnmiUhk7DFaLnRGM4M/I4hYmfPftjlXARKdemvWS1FbdDxuK3pfoi8uvpdk3o2AGryTeKR8TLkd4VLW9LiF01cOZJ9kYgK5H7pf3DbByAxvDWHbVmDJyz/KGjS/atLCRAG/Z9IXBp+7mXIr1polt+6KXAddS32tZyoEyY3Ik/Q/qpH0TxSRn5rfmld2X1XElGh2FoUcJZCfBb/jSaVfS3ZsFYsMqQpUM5M/hmj7w4junRDxxCoPGh08Gz/LaOBbNAAGhhrnxQMYvoKZQy9YdjjTD2y9Ky97BAvn+hDaLofxdXGUzWHz3H0W+v2yZpjY50redki1kp691Y+5/0IdjKCdx+lDG4bJnASzC2ICqU/0BkdhGpnmyQxTAjV9elUHcE1lb6vnOsyNCu4yYABPS6nhh5ZR/TuUqTeo5WRWg40dp1ZmFryjQrmTxR5t3MVqAzDsdWND7Tc4yI1CM=
  on:
    branch: master
    python: '3.6'
