language: python
python:
- '3.6'
- '3.5'
- '2.7'
sudo: required
services:
- docker
install:
- pip install -r requirements.txt
before_script:
- docker run -d -p 127.0.0.1:1883:1883 thethingsnetwork/rabbitmq
script:
- pycodestyle --first src
before_deploy:
- python setup.py sdist
- python setup.py bdist_wheel --universal
deploy:
  provider: pypi
  user: emmlejeail
  password:
    secure: hTaspty3uemb7Wr/oQeiV8i8wM4uXR6XugA97FZ2Xy0Pvg0Muvv2Psxi24mre/rt1wlllMwCXgC5aVymq7xfC75NoLDINOuKEf+9ixbVTehei0ZkkzTVmrBzfr2g3O2qGBJ9M6sD9jehnq4ewgYNWL+DO5l7Spjd1+6uNhzpit+4F3wP+NbZKxBCjfXrkEalpy4MbpjFDZxZUkmBZ2Hyy4ECubi30b+kw6PS68w0tg3VuxqOnx9JXyel6PWnwSwXdtalyUwLr8dT0C6MY1LiikzDuA1tfSLN8XNoqqPWyh856iyRvkOWXBlEkLrwogGQw/UbYpBsvjj4YEtbdHmnOJ04+yQPUJ5xQbLKSL6zpGTDnVPQT7pf+nPyEO3nCOD6/NGur0u+HMiZlyxj8A0xQBWWb+ghkkybztvsDlE9CTXwvtBIF6CZGqvkiyDsJjxK/D8hfWnSODAH+5GNNQhYI89ZdmXKC8sKLr2JQcGj8Yr1Hxqq6dfPnNb2D12yw0wgrfnLr25llsgAjmcV7AtsyHppEZsCYJJ9vGyPVglC1d5UOEETrRAVduVLAvSA/a+LkugOyhQF9GdwLO0oVeeTneQ96xpZNaRGeN6m8iSgvpovHCASgw1IMhAkiZy/U0i7fE5lL2011Luym1AlNfFKlkhWarj7wdOXIoXL1SGzZH4=
  on:
    branch: master
    python: '3.6'
